# Generated by Django 3.2.8 on 2021-12-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_club', '0002_auto_20211214_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('place', models.CharField(max_length=200)),
            ],
        ),
    ]
